# Generated by Django 5.2.4 on 2026-07-11 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم العربي')),
                ('unit_type', models.CharField(choices=[('sector', 'قطاع'), ('directorate', 'إدارة'), ('department', 'قسم'), ('unit', 'وحدة')], max_length=20, verbose_name='نوع الوحدة')),
                ('path_cache', models.CharField(blank=True, editable=False, max_length=1000, null=True, verbose_name='المسار المخبأ')),
                ('level', models.PositiveSmallIntegerField(default=0, verbose_name='المستوى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('valid_from', models.DateField(verbose_name='صالح من')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='صالح حتى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الأرشفة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.department', verbose_name='الوحدة الأم')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر من عدله')),
            ],
            options={
                'verbose_name': 'وحدة تنظيمية',
                'verbose_name_plural': 'الوحدات التنظيمية',
                'db_table': 'departments',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='UserDepartmentScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('include_descendants', models.BooleanField(default=False, verbose_name='يشمل الوحدات الفرعية')),
                ('access_level', models.CharField(choices=[('view', 'عرض'), ('manage', 'إدارة'), ('approve', 'اعتماد')], max_length=20, verbose_name='مستوى الوصول')),
                ('valid_from', models.DateTimeField(verbose_name='صالح من')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='صالح حتى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_scopes_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('department', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='user_scopes', to='organization.department', verbose_name='الوحدة التنظيمية')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_scopes', to='accounts.role', verbose_name='الدور')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='department_scopes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نطاق وحدة تنظيمية',
                'verbose_name_plural': 'نطاقات الوحدات التنظيمية',
                'db_table': 'user_department_scopes',
                'ordering': ('user_id', 'department_id', 'valid_from'),
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active', 'archived_at'], name='dept_active_archive_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='dept_no_self_parent_ck'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='dept_valid_period_ck'),
        ),
        migrations.AddIndex(
            model_name='userdepartmentscope',
            index=models.Index(fields=['user', 'valid_from', 'valid_to'], name='scope_user_valid_idx'),
        ),
        migrations.AddIndex(
            model_name='userdepartmentscope',
            index=models.Index(fields=['department', 'valid_from', 'valid_to'], name='scope_dept_valid_idx'),
        ),
        migrations.AddConstraint(
            model_name='userdepartmentscope',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', True)), fields=('user', 'department', 'access_level', 'valid_from'), name='scope_uniq_without_role'),
        ),
        migrations.AddConstraint(
            model_name='userdepartmentscope',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('user', 'department', 'role', 'access_level', 'valid_from'), name='scope_uniq_with_role'),
        ),
        migrations.AddConstraint(
            model_name='userdepartmentscope',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='scope_valid_period_ck'),
        ),
    ]
