# Generated by Django 5.2.16 on 2026-07-11 20:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الوظيفي')),
                ('full_name_ar', models.CharField(max_length=250, verbose_name='الاسم العربي')),
                ('preferred_name_ar', models.CharField(blank=True, max_length=150, verbose_name='اسم العرض')),
                ('work_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الوظيفي')),
                ('mobile_masked', models.CharField(blank=True, max_length=30, verbose_name='رقم الجوال المقنع')),
                ('employment_status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف'), ('terminated', 'منتهي الخدمة'), ('archived', 'مؤرشف')], default='active', max_length=20, verbose_name='الحالة الوظيفية')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الخدمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الأرشفة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر من عدله')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'db_table': 'employees',
                'ordering': ('full_name_ar',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_type', models.CharField(choices=[('national_id', 'السجل المدني')], default='national_id', max_length=20, verbose_name='نوع الهوية')),
                ('national_id_hash', models.CharField(max_length=64, unique=True, verbose_name='بصمة السجل المدني')),
                ('national_id_encrypted', models.BinaryField(verbose_name='السجل المدني المشفر')),
                ('encryption_key_version', models.CharField(max_length=30, verbose_name='إصدار مفتاح التشفير')),
                ('national_id_last4', models.CharField(max_length=4, verbose_name='آخر أربعة أرقام')),
                ('normalized_length', models.PositiveSmallIntegerField(default=10, verbose_name='طول القيمة بعد التطبيع')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحقق')),
                ('verification_source', models.CharField(blank=True, choices=[('manual', 'إدخال يدوي'), ('import', 'استيراد'), ('integration', 'تكامل')], max_length=50, verbose_name='مصدر التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_identities_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='identity', to='organization.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_identities_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر من عدله')),
            ],
            options={
                'verbose_name': 'هوية موظف',
                'verbose_name_plural': 'هويات الموظفين',
                'db_table': 'employee_identities',
            },
        ),
        migrations.CreateModel(
            name='EmployeeImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('storage_key', models.CharField(max_length=500, unique=True, verbose_name='مفتاح التخزين')),
                ('file_sha256', models.CharField(max_length=64, unique=True, verbose_name='بصمة الملف')),
                ('file_size_bytes', models.PositiveBigIntegerField(verbose_name='حجم الملف بالبايت')),
                ('mime_type', models.CharField(max_length=100, verbose_name='نوع الملف')),
                ('encryption_key_version', models.CharField(max_length=30, verbose_name='إصدار مفتاح التشفير')),
                ('status', models.CharField(choices=[('uploaded', 'مرفوع'), ('preview_ready', 'جاهز للمعاينة'), ('has_errors', 'به أخطاء'), ('approved', 'معتمد'), ('failed', 'فشل')], default='uploaded', max_length=20, verbose_name='الحالة')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='إجمالي الصفوف')),
                ('new_rows', models.PositiveIntegerField(default=0, verbose_name='الموظفون الجدد')),
                ('update_rows', models.PositiveIntegerField(default=0, verbose_name='الموظفون المحدثون')),
                ('missing_department_rows', models.PositiveIntegerField(default=0, verbose_name='الأقسام غير الموجودة')),
                ('missing_location_rows', models.PositiveIntegerField(default=0, verbose_name='المواقع غير الموجودة')),
                ('unmatched_manager_rows', models.PositiveIntegerField(default=0, verbose_name='المديرون غير المطابقين')),
                ('error_rows', models.PositiveIntegerField(default=0, verbose_name='الأخطاء المانعة')),
                ('warning_rows', models.PositiveIntegerField(default=0, verbose_name='التحذيرات')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_imports_approved', to=settings.AUTH_USER_MODEL, verbose_name='معتمد الملف')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_imports_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='رافع الملف')),
            ],
            options={
                'verbose_name': 'دفعة استيراد موظفين',
                'verbose_name_plural': 'دفعات استيراد الموظفين',
                'db_table': 'employee_import_batches',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(verbose_name='رقم الصف')),
                ('raw_payload_encrypted', models.BinaryField(verbose_name='الحمولة الأصلية المشفرة')),
                ('encryption_key_version', models.CharField(max_length=30, verbose_name='إصدار مفتاح التشفير')),
                ('payload_sha256', models.CharField(max_length=64, verbose_name='بصمة الحمولة')),
                ('national_id_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='بصمة السجل المدني')),
                ('national_id_last4', models.CharField(blank=True, max_length=4, verbose_name='آخر أربعة أرقام')),
                ('display_data_json', models.JSONField(default=dict, verbose_name='بيانات العرض المنقحة')),
                ('import_action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('skip', 'تخطي')], default='skip', max_length=20, verbose_name='إجراء الاستيراد')),
                ('validation_status', models.CharField(choices=[('valid', 'صالح'), ('warning', 'تحذير'), ('error', 'خطأ')], default='valid', max_length=20, verbose_name='حالة التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('batch', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='organization.employeeimportbatch', verbose_name='دفعة الاستيراد')),
                ('matched_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_rows', to='organization.employee', verbose_name='الموظف المطابق')),
            ],
            options={
                'verbose_name': 'صف استيراد موظف',
                'verbose_name_plural': 'صفوف استيراد الموظفين',
                'db_table': 'employee_import_rows',
                'ordering': ('batch_id', 'row_number'),
            },
        ),
        migrations.CreateModel(
            name='EmployeeImportError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_code', models.CharField(max_length=80, verbose_name='رمز الخطأ')),
                ('severity', models.CharField(choices=[('warning', 'تحذير'), ('error', 'خطأ مانع')], max_length=20, verbose_name='درجة الخطأ')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='اسم الحقل')),
                ('message_ar', models.CharField(max_length=500, verbose_name='رسالة الخطأ')),
                ('masked_value', models.CharField(blank=True, max_length=255, verbose_name='القيمة المقنعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('batch', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='errors', to='organization.employeeimportbatch', verbose_name='دفعة الاستيراد')),
                ('row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='errors', to='organization.employeeimportrow', verbose_name='صف الاستيراد')),
            ],
            options={
                'verbose_name': 'خطأ استيراد موظف',
                'verbose_name_plural': 'أخطاء استيراد الموظفين',
                'db_table': 'employee_import_errors',
                'ordering': ('batch_id', 'row_id', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=200, verbose_name='المسمى العربي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_titles_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_titles_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر من عدله')),
            ],
            options={
                'verbose_name': 'مسمى وظيفي',
                'verbose_name_plural': 'المسميات الوظيفية',
                'db_table': 'job_titles',
                'ordering': ('name_ar',),
            },
        ),
        migrations.CreateModel(
            name='EmploymentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('primary', 'أساسي'), ('acting', 'تكليف'), ('secondment', 'ندب')], default='primary', max_length=20, verbose_name='نوع الإسناد')),
                ('valid_from', models.DateField(verbose_name='صالح من')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='صالح حتى')),
                ('is_primary', models.BooleanField(default=True, verbose_name='إسناد أساسي')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('department', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='employment_assignments', to='organization.department', verbose_name='الوحدة التنظيمية')),
                ('employee', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='employment_assignments', to='organization.employee', verbose_name='الموظف')),
                ('manager_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_employment_assignments', to='organization.employee', verbose_name='المدير المباشر')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_assignments_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر من عدله')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employment_assignments', to='organization.jobtitle', verbose_name='المسمى الوظيفي')),
            ],
            options={
                'verbose_name': 'إسناد وظيفي',
                'verbose_name_plural': 'الإسنادات الوظيفية',
                'db_table': 'employment_assignments',
                'ordering': ('employee_id', '-valid_from'),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم العربي')),
                ('location_type', models.CharField(choices=[('headquarters', 'مقر'), ('branch', 'فرع'), ('field', 'موقع ميداني')], max_length=20, verbose_name='نوع الموقع')),
                ('address_ar', models.TextField(blank=True, verbose_name='العنوان')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=50, verbose_name='المنطقة الزمنية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('department', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organization.department', verbose_name='الجهة المالكة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر من عدله')),
            ],
            options={
                'verbose_name': 'موقع',
                'verbose_name_plural': 'المواقع',
                'db_table': 'locations',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='EmployeePrimaryLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateField(verbose_name='صالح من')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='صالح حتى')),
                ('assignment_reason', models.TextField(blank=True, verbose_name='سبب الإسناد')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_locations_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('employee', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='primary_location_assignments', to='organization.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_locations_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر من عدله')),
                ('location', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='organization.location', verbose_name='الموقع الأساسي')),
            ],
            options={
                'verbose_name': 'موقع موظف أساسي',
                'verbose_name_plural': 'مواقع الموظفين الأساسية',
                'db_table': 'employee_primary_locations',
                'ordering': ('employee_id', '-valid_from'),
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employment_status', 'archived_at'], name='emp_status_archive_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['full_name_ar'], name='emp_full_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_number__isnull', False)), fields=('employee_number',), name='emp_number_present_uq'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('employee_number__isnull', True), models.Q(('employee_number', ''), _negated=True), _connector='OR'), name='emp_number_not_empty_ck'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('termination_date__isnull', True), ('hire_date__isnull', True), ('termination_date__gte', models.F('hire_date')), _connector='OR'), name='emp_employment_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='employeeidentity',
            constraint=models.CheckConstraint(condition=models.Q(('identity_type', 'national_id')), name='emp_identity_type_ck'),
        ),
        migrations.AddConstraint(
            model_name='employeeidentity',
            constraint=models.CheckConstraint(condition=models.Q(('national_id_last4__regex', '^[0-9]{4}$')), name='emp_identity_last4_ck'),
        ),
        migrations.AddConstraint(
            model_name='employeeidentity',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_length', 10)), name='emp_identity_length_ck'),
        ),
        migrations.AddIndex(
            model_name='employeeimportbatch',
            index=models.Index(fields=['status', 'created_at'], name='emp_import_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeimportbatch',
            constraint=models.CheckConstraint(condition=models.Q(('file_size_bytes__gt', 0)), name='emp_import_batch_size_ck'),
        ),
        migrations.AddConstraint(
            model_name='employeeimportbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), ('approved_at__isnull', False)), models.Q(models.Q(('status', 'approved'), _negated=True), ('approved_at__isnull', True)), _connector='OR'), name='emp_import_approval_ck'),
        ),
        migrations.AddIndex(
            model_name='employeeimportrow',
            index=models.Index(fields=['batch', 'validation_status'], name='emp_import_row_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeimportrow',
            index=models.Index(fields=['national_id_hash'], name='emp_import_row_nid_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeimportrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='emp_import_row_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='employeeimportrow',
            constraint=models.CheckConstraint(condition=models.Q(('row_number__gt', 0)), name='emp_import_row_number_ck'),
        ),
        migrations.AddConstraint(
            model_name='employeeimportrow',
            constraint=models.CheckConstraint(condition=models.Q(('national_id_last4', ''), ('national_id_last4__regex', '^[0-9]{4}$'), _connector='OR'), name='emp_import_row_last4_ck'),
        ),
        migrations.AddIndex(
            model_name='employeeimporterror',
            index=models.Index(fields=['batch', 'severity'], name='emp_import_error_sev_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeimporterror',
            index=models.Index(fields=['error_code'], name='emp_import_error_code_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentassignment',
            index=models.Index(fields=['employee', 'valid_from', 'valid_to'], name='emp_assign_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentassignment',
            index=models.Index(fields=['department', 'valid_from', 'valid_to'], name='emp_assign_dept_idx'),
        ),
        migrations.AddConstraint(
            model_name='employmentassignment',
            constraint=models.UniqueConstraint(fields=('employee', 'valid_from', 'assignment_type', 'department'), name='emp_assign_natural_uq'),
        ),
        migrations.AddConstraint(
            model_name='employmentassignment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='emp_assign_period_ck'),
        ),
        migrations.AddConstraint(
            model_name='employmentassignment',
            constraint=models.CheckConstraint(condition=models.Q(('manager_employee__isnull', True), models.Q(('manager_employee', models.F('employee')), _negated=True), _connector='OR'), name='emp_assign_not_self_mgr_ck'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['department', 'is_active'], name='loc_dept_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='loc_latitude_range_ck'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='loc_longitude_range_ck'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('timezone', 'Asia/Riyadh')), name='loc_timezone_riyadh_ck'),
        ),
        migrations.AddIndex(
            model_name='employeeprimarylocation',
            index=models.Index(fields=['employee', 'valid_from', 'valid_to'], name='emp_location_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprimarylocation',
            index=models.Index(fields=['location', 'valid_from', 'valid_to'], name='emp_location_location_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeprimarylocation',
            constraint=models.UniqueConstraint(fields=('employee', 'location', 'valid_from'), name='emp_location_natural_uq'),
        ),
        migrations.AddConstraint(
            model_name='employeeprimarylocation',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='emp_location_period_ck'),
        ),
    ]
