# Generated by Django 5.2.16 on 2026-08-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_employee_employeeidentity_employeeimportbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='headed_departments', to='organization.employee', verbose_name='رئيس القسم'),
        ),
        migrations.AddField(
            model_name='department',
            name='signing_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signing_departments', to='organization.location', verbose_name='مكان التوقيع'),
        ),
    ]
