# Generated by Django 5.2.4 on 2026-07-11 18:54

import accounts.models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='اسم المستخدم')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='اسم العائلة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دخول الإدارة')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدير نظام')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='يلزم تغيير كلمة المرور')),
                ('failed_login_count', models.PositiveSmallIntegerField(default=0, verbose_name='محاولات الدخول الفاشلة')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='القفل حتى')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تغيير لكلمة المرور')),
                ('locale', models.CharField(default='ar', max_length=10, verbose_name='اللغة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الأرشفة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_users', to=settings.AUTH_USER_MODEL, verbose_name='حدّثه')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'db_table': 'users',
                'ordering': ('username',),
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True, verbose_name='الرمز')),
                ('module', models.CharField(max_length=50, verbose_name='الوحدة')),
                ('action', models.CharField(max_length=50, verbose_name='الإجراء')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم العربي')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'صلاحية',
                'verbose_name_plural': 'الصلاحيات',
                'db_table': 'permissions',
                'ordering': ('module', 'action'),
                'indexes': [models.Index(fields=['module', 'is_active'], name='acct_perm_module_active_ix')],
                'constraints': [models.UniqueConstraint(fields=('module', 'action'), name='acct_perm_module_action_uq')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم العربي')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_system', models.BooleanField(default=False, verbose_name='دور نظام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_roles', to=settings.AUTH_USER_MODEL, verbose_name='حدّثه')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
                'db_table': 'roles',
                'ordering': ('name_ar',),
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ المنح')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_permissions', to=settings.AUTH_USER_MODEL, verbose_name='منحها')),
                ('permission', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='accounts.permission', verbose_name='الصلاحية')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_role_permissions', to=settings.AUTH_USER_MODEL, verbose_name='ألغاها')),
                ('role', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='permission_assignments', to='accounts.role', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'صلاحية دور',
                'verbose_name_plural': 'صلاحيات الأدوار',
                'db_table': 'role_permissions',
                'ordering': ('role__name_ar', 'permission__module', 'permission__action'),
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ساري من')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='ساري إلى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_roles', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='accounts.role', verbose_name='الدور')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'دور مستخدم',
                'verbose_name_plural': 'أدوار المستخدمين',
                'db_table': 'user_roles',
                'ordering': ('user__username', 'role__name_ar', '-valid_from'),
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'archived_at'], name='acct_user_active_arch_ix'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(django.db.models.functions.text.Lower('email'), name='acct_user_email_lower_ix'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='acct_user_username_ci_uq'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('locale', 'ar')), name='acct_user_locale_ar_ck'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'revoked_at'], name='acct_rp_role_rev_ix'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission', 'revoked_at'], name='acct_rp_perm_rev_ix'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('role', 'permission'), name='acct_rp_active_uq'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.CheckConstraint(condition=models.Q(('revoked_by__isnull', True), ('revoked_at__isnull', False), _connector='OR'), name='acct_rp_revoke_data_ck'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_at__gte', models.F('granted_at')), _connector='OR'), name='acct_rp_revoke_time_ck'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active', 'valid_from', 'valid_to'], name='acct_ur_user_dates_ix'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'valid_from'), name='acct_ur_user_role_from_uq'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='acct_ur_dates_ck'),
        ),
    ]
