# Generated by Django 5.2.4 on 2026-07-11 18:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='وقت الحدث')),
                ('actor_username_snapshot', models.CharField(blank=True, max_length=150, null=True, verbose_name='لقطة اسم المستخدم')),
                ('action', models.CharField(max_length=100, verbose_name='الإجراء')),
                ('module', models.CharField(max_length=50, verbose_name='الوحدة')),
                ('object_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الكيان')),
                ('object_id', models.UUIDField(blank=True, null=True, verbose_name='معرّف الكيان')),
                ('object_repr_masked', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف الكيان المقنّع')),
                ('before_json', models.JSONField(blank=True, null=True, verbose_name='القيم السابقة')),
                ('after_json', models.JSONField(blank=True, null=True, verbose_name='القيم اللاحقة')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='السبب')),
                ('outcome', models.CharField(choices=[('success', 'نجاح'), ('failure', 'فشل'), ('permission_denied', 'رفض صلاحية')], max_length=20, verbose_name='النتيجة')),
                ('request_id', models.UUIDField(blank=True, null=True, verbose_name='معرّف الطلب')),
                ('session_key_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='بصمة الجلسة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='عنوان الشبكة')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='وكيل المستخدم')),
                ('integrity_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='بصمة السلامة')),
                ('actor_user', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المنفذ')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'db_table': 'audit_logs',
                'ordering': ('-occurred_at',),
            },
        ),
    ]
