# Generated by Django 5.2.4 on 2026-07-11 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='department_scope',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='organization.department', verbose_name='نطاق القسم'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-occurred_at'], name='audit_occurred_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_user', '-occurred_at'], name='audit_actor_occur_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type', 'object_id', 'occurred_at'], name='audit_object_occur_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['department_scope', 'occurred_at'], name='audit_dept_occur_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'outcome', 'occurred_at'], name='audit_action_outcome_idx'),
        ),
    ]
