# Generated by Django 5.2.16 on 2026-07-12 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_employee_employeeidentity_employeeimportbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('storage_key', models.CharField(max_length=500, unique=True, verbose_name='مفتاح التخزين')),
                ('file_sha256', models.CharField(max_length=64, unique=True, verbose_name='بصمة الملف')),
                ('file_size_bytes', models.PositiveBigIntegerField(verbose_name='حجم الملف')),
                ('mime_type', models.CharField(max_length=100, verbose_name='نوع الملف')),
                ('template_version', models.CharField(default='weekly_summary_v1', max_length=30, verbose_name='إصدار القالب')),
                ('source_name', models.CharField(default='تقرير البصمة الأسبوعي', max_length=100, verbose_name='مصدر الملف')),
                ('source_period_title', models.CharField(blank=True, max_length=255, verbose_name='عنوان الفترة')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='بداية الفترة')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='نهاية الفترة')),
                ('status', models.CharField(choices=[('uploaded', 'مرفوع'), ('preview_ready', 'جاهز للمعاينة'), ('has_errors', 'به أخطاء'), ('approved', 'معتمد'), ('failed', 'فشل')], default='uploaded', max_length=20, verbose_name='الحالة')),
                ('source_row_count', models.PositiveIntegerField(default=0, verbose_name='صفوف المصدر')),
                ('employee_count', models.PositiveIntegerField(default=0, verbose_name='عدد الموظفين')),
                ('daily_record_count', models.PositiveIntegerField(default=0, verbose_name='سجلات الأيام')),
                ('matched_row_count', models.PositiveIntegerField(default=0, verbose_name='السجلات المطابقة')),
                ('unmatched_row_count', models.PositiveIntegerField(default=0, verbose_name='السجلات غير المطابقة')),
                ('ignored_row_count', models.PositiveIntegerField(default=0, verbose_name='الصفوف المتجاهلة')),
                ('summary_row_count', models.PositiveIntegerField(default=0, verbose_name='صفوف المجموع')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='الأخطاء')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='التحذيرات')),
                ('distinct_location_count', models.PositiveIntegerField(default=0, verbose_name='المواقع المختلفة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_imports_approved', to=settings.AUTH_USER_MODEL, verbose_name='معتمد الملف')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_imports_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='رافع الملف')),
            ],
            options={
                'verbose_name': 'دفعة استيراد حضور',
                'verbose_name_plural': 'دفعات استيراد الحضور',
                'db_table': 'import_batches',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(verbose_name='رقم الصف')),
                ('raw_payload_encrypted', models.BinaryField(verbose_name='الصف الأصلي المشفر')),
                ('encryption_key_version', models.CharField(max_length=30, verbose_name='إصدار المفتاح')),
                ('raw_payload_sha256', models.CharField(max_length=64, verbose_name='بصمة الصف')),
                ('schema_version', models.CharField(default='weekly_summary_v1', max_length=30, verbose_name='إصدار المخطط')),
                ('national_id_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='بصمة السجل المدني')),
                ('national_id_last4', models.CharField(blank=True, max_length=4, verbose_name='آخر أربعة أرقام')),
                ('normalized_payload_json', models.JSONField(default=dict, verbose_name='البيانات المطبعة')),
                ('display_data_json', models.JSONField(default=dict, verbose_name='بيانات العرض المنقحة')),
                ('attendance_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الحضور')),
                ('source_check_in', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('source_check_out', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('source_check_in_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='مكان الحضور')),
                ('source_check_out_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='مكان الانصراف')),
                ('source_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='حالة المصدر')),
                ('source_scheduled_duration', models.DurationField(blank=True, null=True, verbose_name='مدة الدوام المصدرية')),
                ('source_actual_work_duration', models.DurationField(blank=True, null=True, verbose_name='مدة العمل المصدرية')),
                ('source_early_departure_duration', models.DurationField(blank=True, null=True, verbose_name='الانصراف المبكر المصدري')),
                ('source_shortfall_duration', models.DurationField(blank=True, null=True, verbose_name='نقص الدوام المصدري')),
                ('source_early_arrival_duration', models.DurationField(blank=True, null=True, verbose_name='الحضور المبكر المصدري')),
                ('proposed_record_fingerprint', models.CharField(blank=True, max_length=64, null=True, verbose_name='بصمة السجل المقترحة')),
                ('match_status', models.CharField(choices=[('matched', 'مطابق'), ('unmatched', 'غير مطابق'), ('invalid', 'غير صالح')], max_length=20, verbose_name='حالة المطابقة')),
                ('validation_status', models.CharField(choices=[('valid', 'صالح'), ('warning', 'تحذير'), ('error', 'خطأ')], max_length=20, verbose_name='حالة التحقق')),
                ('location_match_status', models.CharField(choices=[('matched', 'مطابق'), ('mismatch', 'موقع مختلف'), ('unknown', 'غير معروف'), ('not_required', 'غير مطلوب')], default='unknown', max_length=20, verbose_name='حالة الموقع')),
                ('is_duplicate', models.BooleanField(default=False, verbose_name='سجل مكرر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التسجيل')),
                ('batch', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='attendance.importbatch', verbose_name='دفعة الاستيراد')),
                ('matched_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_import_rows', to='organization.employee', verbose_name='الموظف المطابق')),
            ],
            options={
                'verbose_name': 'صف استيراد حضور',
                'verbose_name_plural': 'صفوف استيراد الحضور',
                'db_table': 'import_rows',
                'ordering': ('batch_id', 'row_number'),
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_code', models.CharField(max_length=80, verbose_name='رمز الخطأ')),
                ('severity', models.CharField(choices=[('warning', 'تحذير'), ('error', 'خطأ مانع')], max_length=20, verbose_name='الدرجة')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='الحقل')),
                ('message_ar', models.CharField(max_length=500, verbose_name='الرسالة')),
                ('masked_value', models.CharField(blank=True, max_length=255, verbose_name='القيمة المقنعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التسجيل')),
                ('batch', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='errors', to='attendance.importbatch', verbose_name='دفعة الاستيراد')),
                ('row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='errors', to='attendance.importrow', verbose_name='صف الاستيراد')),
            ],
            options={
                'verbose_name': 'خطأ استيراد حضور',
                'verbose_name_plural': 'أخطاء استيراد الحضور',
                'db_table': 'import_errors',
                'ordering': ('batch_id', 'row_id', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='RawAttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('national_id_hash', models.CharField(max_length=64, verbose_name='بصمة السجل المدني')),
                ('attendance_date', models.DateField(verbose_name='تاريخ الحضور')),
                ('source_check_in_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحضور المصدري')),
                ('source_check_out_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانصراف المصدري')),
                ('source_check_in_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='مكان الحضور')),
                ('source_check_out_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='مكان الانصراف')),
                ('source_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='حالة المصدر')),
                ('source_scheduled_duration', models.DurationField(blank=True, null=True, verbose_name='مدة الدوام المصدرية')),
                ('source_actual_work_duration', models.DurationField(blank=True, null=True, verbose_name='مدة العمل المصدرية')),
                ('source_early_departure_duration', models.DurationField(blank=True, null=True, verbose_name='الانصراف المبكر المصدري')),
                ('source_shortfall_duration', models.DurationField(blank=True, null=True, verbose_name='نقص الدوام المصدري')),
                ('source_early_arrival_duration', models.DurationField(blank=True, null=True, verbose_name='الحضور المبكر المصدري')),
                ('record_fingerprint', models.CharField(max_length=64, unique=True, verbose_name='بصمة السجل')),
                ('match_status', models.CharField(choices=[('matched', 'مطابق')], default='matched', max_length=20, verbose_name='حالة المطابقة')),
                ('location_match_status', models.CharField(choices=[('matched', 'مطابق'), ('mismatch', 'موقع مختلف'), ('unknown', 'غير معروف'), ('not_required', 'غير مطلوب')], max_length=20, verbose_name='حالة الموقع')),
                ('matched_at', models.DateTimeField(verbose_name='وقت المطابقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_attendance_records', to='organization.employee', verbose_name='الموظف')),
                ('import_row', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='raw_record', to='attendance.importrow', verbose_name='صف الاستيراد')),
                ('primary_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_attendance_primary_location_records', to='organization.location', verbose_name='الموقع الأساسي النافذ')),
            ],
            options={
                'verbose_name': 'سجل حضور خام',
                'verbose_name_plural': 'سجلات الحضور الخام',
                'db_table': 'raw_attendance_records',
                'ordering': ('-attendance_date', 'employee_id'),
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['status', 'created_at'], name='att_import_status_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['period_start', 'period_end'], name='att_import_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('file_size_bytes__gt', 0)), name='att_import_size_ck'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__isnull', True), ('period_end__isnull', True), ('period_end__gte', models.F('period_start')), _connector='OR'), name='att_import_period_ck'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), ('approved_at__isnull', False)), models.Q(models.Q(('status', 'approved'), _negated=True), ('approved_at__isnull', True)), _connector='OR'), name='att_import_approval_ck'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['batch', 'validation_status'], name='att_row_valid_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['batch', 'match_status'], name='att_row_match_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['national_id_hash'], name='att_row_nid_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='att_import_row_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.CheckConstraint(condition=models.Q(('row_number__gt', 0)), name='att_import_row_number_ck'),
        ),
        migrations.AddIndex(
            model_name='importerror',
            index=models.Index(fields=['batch', 'severity'], name='att_error_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='importerror',
            index=models.Index(fields=['error_code'], name='att_error_code_idx'),
        ),
        migrations.AddIndex(
            model_name='rawattendancerecord',
            index=models.Index(fields=['employee', 'attendance_date'], name='raw_att_emp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='rawattendancerecord',
            index=models.Index(fields=['national_id_hash'], name='raw_att_nid_idx'),
        ),
        migrations.AddIndex(
            model_name='rawattendancerecord',
            index=models.Index(fields=['location_match_status', 'attendance_date'], name='raw_att_loc_status_idx'),
        ),
    ]
