# Generated by Django 5.2.16 on 2026-07-12 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('organization', '0002_employee_employeeidentity_employeeimportbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_type', models.CharField(choices=[('initial', 'احتساب أولي'), ('recalculation', 'إعادة احتساب')], default='initial', max_length=20, verbose_name='نوع التشغيل')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('status', models.CharField(choices=[('pending', 'مجدول'), ('running', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('rules_version', models.CharField(default='v1', max_length=30, verbose_name='إصدار القواعد')),
                ('reason', models.TextField(blank=True, verbose_name='سبب التشغيل')),
                ('result_count', models.PositiveIntegerField(default=0, verbose_name='عدد النتائج')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('failure_summary', models.TextField(blank=True, verbose_name='ملخص الفشل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الطلب')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_runs', to='attendance.importbatch', verbose_name='دفعة الاستيراد')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_calculation_runs', to=settings.AUTH_USER_MODEL, verbose_name='طالب الاحتساب')),
            ],
            options={
                'verbose_name': 'تشغيل احتساب حضور',
                'verbose_name_plural': 'تشغيلات احتساب الحضور',
                'db_table': 'calculation_runs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DailyAttendanceResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(verbose_name='التاريخ')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='الإصدار')),
                ('is_current', models.BooleanField(default=True, verbose_name='الإصدار الحالي')),
                ('first_check_in_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('last_check_out_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('check_in_location', models.CharField(blank=True, max_length=255, verbose_name='مكان الحضور')),
                ('check_out_location', models.CharField(blank=True, max_length=255, verbose_name='مكان الانصراف')),
                ('scheduled_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق الدوام المجدولة')),
                ('worked_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق العمل الفعلية')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق التأخر')),
                ('early_leave_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق الانصراف المبكر')),
                ('shortfall_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق النقص')),
                ('early_arrival_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق الحضور المبكر')),
                ('overtime_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق العمل الإضافي')),
                ('attendance_status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غياب'), ('excused', 'مستثنى'), ('incomplete', 'بصمة ناقصة'), ('unknown', 'غير محدد')], max_length=20, verbose_name='حالة اليوم')),
                ('check_in_location_matches', models.BooleanField(blank=True, null=True, verbose_name='مكان الحضور مطابق')),
                ('check_out_location_matches', models.BooleanField(blank=True, null=True, verbose_name='مكان الانصراف مطابق')),
                ('location_status', models.CharField(choices=[('matched', 'الموقعان مطابقان'), ('check_in_outside', 'الحضور خارج الموقع'), ('check_out_outside', 'الانصراف خارج الموقع'), ('both_outside', 'الحضور والانصراف خارج الموقع'), ('unknown', 'موقع غير معروف'), ('not_required', 'لا يوجد موقع معتمد')], max_length=30, verbose_name='حالة الموقع')),
                ('source_status', models.CharField(blank=True, max_length=100, verbose_name='حالة المصدر')),
                ('calculation_notes', models.JSONField(default=dict, verbose_name='تفاصيل الاحتساب')),
                ('superseded_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاستبدال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('calculation_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='attendance.calculationrun', verbose_name='تشغيل الاحتساب')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendance_results', to='organization.department', verbose_name='القسم وقت الحضور')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendance_results', to='organization.employee', verbose_name='الموظف')),
                ('primary_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendance_results', to='organization.location', verbose_name='الموقع المعتمد')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_results', to='attendance.rawattendancerecord', verbose_name='السجل الخام')),
            ],
            options={
                'verbose_name': 'نتيجة حضور يومية',
                'verbose_name_plural': 'نتائج الحضور اليومية',
                'db_table': 'daily_attendance_results',
                'ordering': ('-attendance_date', 'employee__full_name_ar'),
            },
        ),
        migrations.AddIndex(
            model_name='calculationrun',
            index=models.Index(fields=['status', 'created_at'], name='calc_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='calculationrun',
            index=models.Index(fields=['period_start', 'period_end'], name='calc_run_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='calculationrun',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='calc_run_period_ck'),
        ),
        migrations.AddIndex(
            model_name='dailyattendanceresult',
            index=models.Index(fields=['employee', 'attendance_date'], name='daily_result_emp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendanceresult',
            index=models.Index(fields=['department', 'attendance_date', 'is_current'], name='daily_result_dept_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendanceresult',
            index=models.Index(fields=['attendance_status', 'attendance_date'], name='daily_result_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendanceresult',
            index=models.Index(fields=['location_status', 'attendance_date'], name='daily_result_location_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyattendanceresult',
            constraint=models.UniqueConstraint(fields=('employee', 'attendance_date', 'version'), name='daily_result_version_uq'),
        ),
        migrations.AddConstraint(
            model_name='dailyattendanceresult',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('employee', 'attendance_date'), name='daily_result_current_uq'),
        ),
        migrations.AddConstraint(
            model_name='dailyattendanceresult',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='daily_result_version_ck'),
        ),
    ]
