# Generated by Django 5.2.16 on 2026-08-09 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_calculationrun_dailyattendanceresult_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='archive_reason',
            field=models.TextField(blank=True, verbose_name='سبب الأرشفة'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الأرشفة'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_imports_archived', to=settings.AUTH_USER_MODEL, verbose_name='أرشفها'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='الاسم الظاهر'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('archived_at__isnull', True), models.Q(('archived_by__isnull', False), models.Q(('archive_reason', ''), _negated=True)), _connector='OR'), name='att_import_archive_data_ck'),
        ),
    ]
