# Generated by Django 5.2.16 on 2026-08-06 10:43

import django.db.models.deletion
import django.utils.timezone
import uuid
import violations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_calculationrun_dailyattendanceresult_and_more'),
        ('organization', '0003_department_department_head_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClarificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(verbose_name='تاريخ الحالة')),
                ('kind', models.CharField(choices=[('absence', 'غياب'), ('outside_location', 'توقيع خارج الموقع'), ('automatic_checkout', 'انصراف تلقائي')], max_length=30, verbose_name='نوع الإفادة')),
                ('status', models.CharField(choices=[('awaiting_employee', 'بانتظار إفادة الموظف'), ('awaiting_manager', 'بانتظار اعتماد رئيس القسم'), ('returned', 'معادة للاستكمال'), ('approved', 'معتمدة'), ('rejected', 'مرفوضة'), ('cancelled', 'ألغيت بإعادة الاحتساب')], default='awaiting_employee', max_length=30, verbose_name='الحالة')),
                ('employee_explanation', models.TextField(blank=True, verbose_name='مبرر الموظف')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت إرسال الإفادة')),
                ('review_comment', models.TextField(blank=True, verbose_name='تعليق رئيس القسم')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القرار')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الإرسال التلقائي')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('attendance_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clarification_requests', to='attendance.dailyattendanceresult', verbose_name='نتيجة الحضور')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clarification_requests', to='organization.department', verbose_name='القسم وقت المخالفة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clarification_requests', to='organization.employee', verbose_name='الموظف')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clarifications_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
            ],
            options={
                'verbose_name': 'طلب إفادة',
                'verbose_name_plural': 'طلبات الإفادة',
                'db_table': 'clarification_requests',
                'ordering': ('-attendance_result__attendance_date', 'employee__full_name_ar'),
            },
        ),
        migrations.CreateModel(
            name='ClarificationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=violations.models.clarification_evidence_path, verbose_name='الشاهد')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('content_type', models.CharField(max_length=100, verbose_name='نوع المحتوى')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='حجم الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الرفع')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clarification_evidence_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='رافع الملف')),
                ('clarification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_files', to='violations.clarificationrequest', verbose_name='طلب الإفادة')),
            ],
            options={
                'verbose_name': 'شاهد إفادة',
                'verbose_name_plural': 'شواهد الإفادات',
                'db_table': 'clarification_evidence',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='clarificationrequest',
            index=models.Index(fields=['employee', 'status'], name='clar_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clarificationrequest',
            index=models.Index(fields=['department', 'status'], name='clar_dept_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clarificationrequest',
            index=models.Index(fields=['kind', 'status'], name='clar_kind_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='clarificationrequest',
            constraint=models.UniqueConstraint(fields=('employee', 'attendance_date', 'kind'), name='clarification_employee_date_kind_uq'),
        ),
        migrations.AddConstraint(
            model_name='clarificationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', False), _connector='OR'), name='clarification_review_actor_ck'),
        ),
    ]
